// src/lib/components/SitePerformance.svelte
<script lang="ts">
  import Chart from './Chart.svelte';
  import type { SitePerformance, AssetRecord } from '../types';
  import { assetModalStore } from '../stores/assetModalStore';

  export let siteData: SitePerformance[];
  export let records: AssetRecord[] = [];

  $: topSites = siteData.slice(0, 10);

  $: chartData = {
    labels: topSites.map(s => s.siteName.substring(0, 20)),
    datasets: [
      {
        label: 'Total Assets',
        data: topSites.map(s => s.totalAssets),
        backgroundColor: 'rgba(200, 16, 46, 0.8)',
      },
      {
        label: 'Reviewed',
        data: topSites.map(s => s.reviewedAssets),
        backgroundColor: 'rgba(16, 185, 129, 0.8)',
      }
    ]
  };

  $: chartOptions = {
    plugins: {
      title: {
        display: true,
        text: 'Top Sites by Asset Volume'
      },
      legend: {
        display: true,
        position: 'bottom' as const
      }
    },
    scales: {
      y: {
        beginAtZero: true
      }
    },
    indexAxis: 'y' as const
  };

  function getTrendColor(trend: number): string {
    if (trend > 10) return 'var(--success-green)';
    if (trend < -10) return 'var(--danger-red)';
    return 'var(--neutral-500)';
  }

  function getTrendIcon(trend: number): string {
    if (trend > 0) return '↑';
    if (trend < 0) return '↓';
    return '→';
  }

  function handleSiteClick(siteName: string) {
    const siteAssets = records.filter(r => r.siteName === siteName);
    assetModalStore.openAssetList(`Assets for Site: ${siteName}`, siteAssets);
  }
</script>

<div class="site-performance">
  <div class="section-header">
    <h2>Site Performance Analytics</h2>
    <p class="section-subtitle">Clinical site activity and review metrics</p>
  </div>

  <div class="grid grid-cols-2">
    <div class="card">
      <Chart type="bar" data={chartData} options={chartOptions} height="450px" />
    </div>

    <div class="card">
      <h3>Site Performance Table</h3>
      <div class="table-container">
        <table class="performance-table">
          <thead>
            <tr>
              <th>Site Name</th>
              <th>Assets</th>
              <th>Review Rate</th>
              <th>Trend</th>
            </tr>
          </thead>
          <tbody>
            {#each topSites as site, index}
              <tr class="clickable-row" on:click={() => handleSiteClick(site.siteName)} on:keydown={(e) => e.key === 'Enter' && handleSiteClick(site.siteName)} role="button" tabindex="0">
                <td class="site-name">
                  <span class="rank">{index + 1}</span>
                  {site.siteName}
                </td>
                <td class="assets-count">{site.totalAssets}</td>
                <td>
                  <div class="progress-bar">
                    <div class="progress-fill" style="width: {site.reviewRate}%"></div>
                    <span class="progress-text">{site.reviewRate.toFixed(0)}%</span>
                  </div>
                </td>
                <td class="trend-cell">
                  <span
                    class="trend-indicator"
                    style="color: {getTrendColor(site.uploadTrend)}"
                  >
                    {getTrendIcon(site.uploadTrend)} {Math.abs(site.uploadTrend).toFixed(0)}%
                  </span>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<style>
  .site-performance {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .section-header {
    margin-bottom: 0.5rem;
  }

  .section-header h2 {
    margin-bottom: 0.25rem;
  }

  .section-subtitle {
    color: var(--neutral-500);
    font-size: 0.875rem;
  }

  .table-container {
    overflow-x: auto;
    margin-top: 1rem;
  }

  .performance-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
  }

  .performance-table th {
    text-align: left;
    padding: 0.75rem 0.5rem;
    border-bottom: 2px solid var(--neutral-200);
    font-weight: 600;
    color: var(--neutral-700);
    background-color: var(--neutral-50);
  }

  .performance-table td {
    padding: 0.75rem 0.5rem;
    border-bottom: 1px solid var(--neutral-200);
  }

  .performance-table tbody tr:hover {
    background-color: var(--neutral-50);
  }

  .clickable-row {
    cursor: pointer;
    transition: all 0.15s ease;
  }

  .clickable-row:hover {
    background-color: var(--neutral-100);
  }

  .clickable-row:focus {
    outline: 2px solid var(--chilli-red);
    outline-offset: -2px;
  }

  .site-name {
    font-weight: 500;
    max-width: 200px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .rank {
    display: inline-block;
    width: 24px;
    height: 24px;
    background-color: var(--chilli-red);
    color: white;
    border-radius: 50%;
    text-align: center;
    line-height: 24px;
    font-size: 0.75rem;
    margin-right: 0.5rem;
    font-weight: 600;
  }

  .assets-count {
    font-weight: 600;
    color: var(--chilli-red);
  }

  .progress-bar {
    position: relative;
    height: 24px;
    background-color: var(--neutral-100);
    border-radius: 4px;
    overflow: hidden;
    min-width: 100px;
  }

  .progress-fill {
    position: absolute;
    height: 100%;
    background: linear-gradient(90deg, var(--chilli-red), var(--chilli-fuschia));
    transition: width 0.3s ease;
  }

  .progress-text {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--neutral-700);
    z-index: 1;
  }

  .trend-cell {
    text-align: center;
  }

  .trend-indicator {
    font-weight: 600;
    font-size: 0.875rem;
  }
</style>

// apps/dashboard/components/SitePerformance.tsx
'use client';

import { useMemo, useCallback } from 'react';
import { useDashboard } from '../contexts/DashboardContext';
import { Chart } from './Chart';

export function SitePerformance() {
    const {
        sitePerformance,
        filteredRecords,
        isLoading,
        setShowAssetList,
        setAssetListTitle,
        setAssetListRecords,
    } = useDashboard();

    const topSites = useMemo(
        () => sitePerformance.slice(0, 10),
        [sitePerformance]
    );

    const chartData = useMemo(
        () => ({
            labels: topSites.map(s => s.siteName.substring(0, 20)),
            datasets: [
                {
                    label: 'Total Assets',
                    data: topSites.map(s => s.totalAssets),
                    backgroundColor: 'rgba(200, 16, 46, 0.8)',
                },
                {
                    label: 'Reviewed',
                    data: topSites.map(s => s.reviewedAssets),
                    backgroundColor: 'rgba(16, 185, 129, 0.8)',
                },
            ],
        }),
        [topSites]
    );

    const chartOptions = useMemo(
        () => ({
            plugins: {
                title: {
                    display: true,
                    text: 'Top Sites by Asset Volume',
                },
                legend: {
                    display: true,
                    position: 'bottom' as const,
                },
            },
            scales: {
                y: {
                    beginAtZero: true,
                },
            },
            indexAxis: 'y' as const,
        }),
        []
    );

    const getTrendColor = useCallback((trend: number): string => {
        if (trend > 10) return '#10b981';
        if (trend < -10) return '#ef4444';
        return '#6b7280';
    }, []);

    const getTrendIcon = useCallback((trend: number): string => {
        if (trend > 0) return '↑';
        if (trend < 0) return '↓';
        return '→';
    }, []);

    const handleSiteClick = useCallback(
        (siteName: string) => {
            const siteAssets = filteredRecords.filter(
                r => r.siteName === siteName
            );
            setAssetListTitle(`Assets for Site: ${siteName}`);
            setAssetListRecords(siteAssets);
            setShowAssetList(true);
        },
        [
            filteredRecords,
            setAssetListTitle,
            setAssetListRecords,
            setShowAssetList,
        ]
    );

    const handleChartClick = useCallback(
        (data: { label: string; index: number; value: number }) => {
            const site = topSites[data.index];
            if (site) {
                handleSiteClick(site.siteName);
            }
        },
        [topSites, handleSiteClick]
    );

    if (isLoading) {
        return (
            <div className="flex flex-col gap-6">
                <div className="animate-pulse">
                    <div className="h-8 bg-neutral-200 rounded w-64 mb-2"></div>
                    <div className="h-4 bg-neutral-200 rounded w-80"></div>
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    <div className="bg-white rounded-lg shadow-sm p-6 h-96 animate-pulse">
                        <div className="h-full bg-neutral-100 rounded"></div>
                    </div>
                    <div className="bg-white rounded-lg shadow-sm p-6 h-96 animate-pulse">
                        <div className="h-full bg-neutral-100 rounded"></div>
                    </div>
                </div>
            </div>
        );
    }

    if (topSites.length === 0) {
        return (
            <div className="bg-white rounded-lg shadow-sm p-8 text-center">
                <p className="text-neutral-500">No site data available.</p>
            </div>
        );
    }

    return (
        <div className="flex flex-col gap-6">
            <div className="mb-2">
                <h2 className="text-xl font-semibold text-neutral-800 mb-1">
                    Site Performance Analytics
                </h2>
                <p className="text-neutral-500 text-sm">
                    Clinical site activity and review metrics
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="bg-white rounded-lg shadow-sm p-6">
                    <Chart
                        type="bar"
                        data={chartData}
                        options={chartOptions}
                        height="450px"
                        clickable={true}
                        onBarClick={handleChartClick}
                    />
                </div>

                <div className="bg-white rounded-lg shadow-sm p-6">
                    <h3 className="text-lg font-semibold text-neutral-800 mb-4">
                        Site Performance Table
                    </h3>
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="bg-neutral-50">
                                    <th className="text-left py-3 px-2 font-semibold text-neutral-700 border-b-2 border-neutral-200">
                                        Site Name
                                    </th>
                                    <th className="text-left py-3 px-2 font-semibold text-neutral-700 border-b-2 border-neutral-200">
                                        Assets
                                    </th>
                                    <th className="text-left py-3 px-2 font-semibold text-neutral-700 border-b-2 border-neutral-200">
                                        Review Rate
                                    </th>
                                    <th className="text-center py-3 px-2 font-semibold text-neutral-700 border-b-2 border-neutral-200">
                                        Trend
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {topSites.map((site, index) => (
                                    <tr
                                        key={site.siteName}
                                        className="cursor-pointer transition-colors hover:bg-neutral-100 focus:outline focus:outline-2 focus:outline-chilli-red"
                                        onClick={() =>
                                            handleSiteClick(site.siteName)
                                        }
                                        onKeyDown={e =>
                                            e.key === 'Enter' &&
                                            handleSiteClick(site.siteName)
                                        }
                                        tabIndex={0}
                                        role="button"
                                    >
                                        <td className="py-3 px-2 border-b border-neutral-200">
                                            <div className="flex items-center gap-2 font-medium max-w-[200px] overflow-hidden text-ellipsis whitespace-nowrap">
                                                <span className="inline-flex items-center justify-center w-6 h-6 bg-chilli-red text-white rounded-full text-xs font-semibold">
                                                    {index + 1}
                                                </span>
                                                {site.siteName}
                                            </div>
                                        </td>
                                        <td className="py-3 px-2 border-b border-neutral-200 font-semibold text-chilli-red">
                                            {site.totalAssets}
                                        </td>
                                        <td className="py-3 px-2 border-b border-neutral-200">
                                            <div className="relative h-6 bg-neutral-100 rounded overflow-hidden min-w-[100px]">
                                                <div
                                                    className="absolute h-full bg-gradient-to-r from-chilli-red to-pink-500 transition-all duration-300"
                                                    style={{
                                                        width: `${site.reviewRate}%`,
                                                    }}
                                                />
                                                <span className="relative z-10 flex items-center justify-center h-full text-xs font-semibold text-neutral-700">
                                                    {site.reviewRate.toFixed(0)}
                                                    %
                                                </span>
                                            </div>
                                        </td>
                                        <td className="py-3 px-2 border-b border-neutral-200 text-center">
                                            <span
                                                className="font-semibold text-sm"
                                                style={{
                                                    color: getTrendColor(
                                                        site.uploadTrend
                                                    ),
                                                }}
                                            >
                                                {getTrendIcon(site.uploadTrend)}{' '}
                                                {Math.abs(
                                                    site.uploadTrend
                                                ).toFixed(0)}
                                                %
                                            </span>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
}
