// apps/dashboard/components/AssetListModal.tsx
'use client';

import { useState, useMemo, useCallback, useEffect } from 'react';
import { format, parseISO } from 'date-fns';
import type { AssetRecord } from '@cp/types';
import { useDashboard } from '../contexts/DashboardContext';

const PAGE_SIZE = 25;

function formatDate(date: Date | string | null | undefined): string {
    if (!date) return '-';
    try {
        const d = typeof date === 'string' ? parseISO(date) : date;
        return format(d, 'dd/MM/yyyy');
    } catch {
        return '-';
    }
}

export function AssetListModal() {
    const {
        showAssetList,
        setShowAssetList,
        assetListTitle,
        assetListRecords,
        setSelectedAsset,
    } = useDashboard();

    const [searchTerm, setSearchTerm] = useState('');
    const [sortField, setSortField] = useState<keyof AssetRecord>('uploadDate');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');
    const [currentPage, setCurrentPage] = useState(1);

    const handleClose = useCallback(() => {
        setShowAssetList(false);
    }, [setShowAssetList]);

    useEffect(() => {
        if (!showAssetList) {
            setSearchTerm('');
            setCurrentPage(1);
        }
    }, [showAssetList]);

    useEffect(() => {
        setCurrentPage(1);
    }, [searchTerm]);

    useEffect(() => {
        function handleKeydown(e: KeyboardEvent) {
            if (e.key === 'Escape' && showAssetList) {
                handleClose();
            }
        }
        document.addEventListener('keydown', handleKeydown);
        return () => document.removeEventListener('keydown', handleKeydown);
    }, [showAssetList, handleClose]);

    const filteredAssets = useMemo(() => {
        return assetListRecords.filter(asset => {
            if (!searchTerm) return true;
            const term = searchTerm.toLowerCase();
            return (
                asset.assetTitle?.toLowerCase().includes(term) ||
                asset.siteName?.toLowerCase().includes(term) ||
                asset.subjectNumber?.toLowerCase().includes(term) ||
                asset.uploadedBy?.toLowerCase().includes(term) ||
                asset.studyProcedure?.toLowerCase().includes(term)
            );
        });
    }, [assetListRecords, searchTerm]);

    const sortedAssets = useMemo(() => {
        return [...filteredAssets].sort((a, b) => {
            const aVal = a[sortField];
            const bVal = b[sortField];

            if (aVal === null || aVal === undefined) return 1;
            if (bVal === null || bVal === undefined) return -1;

            let comparison = 0;
            if (typeof aVal === 'string' && typeof bVal === 'string') {
                comparison = aVal.localeCompare(bVal);
            } else if (aVal instanceof Date && bVal instanceof Date) {
                comparison = aVal.getTime() - bVal.getTime();
            } else {
                comparison = String(aVal).localeCompare(String(bVal));
            }

            return sortDirection === 'asc' ? comparison : -comparison;
        });
    }, [filteredAssets, sortField, sortDirection]);

    const totalPages = Math.ceil(sortedAssets.length / PAGE_SIZE);
    const paginatedAssets = sortedAssets.slice(
        (currentPage - 1) * PAGE_SIZE,
        currentPage * PAGE_SIZE
    );

    const handleRowClick = useCallback(
        (asset: AssetRecord) => {
            setSelectedAsset(asset);
        },
        [setSelectedAsset]
    );

    const handleViewAsset = useCallback(
        (event: React.MouseEvent, asset: AssetRecord) => {
            event.stopPropagation();
            if (asset.assetLink) {
                window.open(asset.assetLink, '_blank', 'noopener,noreferrer');
            }
        },
        []
    );

    const handleSort = useCallback(
        (field: keyof AssetRecord) => {
            if (sortField === field) {
                setSortDirection(previous =>
                    previous === 'asc' ? 'desc' : 'asc'
                );
            } else {
                setSortField(field);
                setSortDirection('desc');
            }
        },
        [sortField]
    );

    const goToPage = useCallback(
        (page: number) => {
            if (page >= 1 && page <= totalPages) {
                setCurrentPage(page);
            }
        },
        [totalPages]
    );

    const exportToCsv = useCallback(() => {
        const headers = [
            'Asset Title',
            'Site Name',
            'Site Country',
            'Subject Number',
            'Study Arm',
            'Study Event',
            'Study Procedure',
            'Procedure Date',
            'Upload Date',
            'Uploaded By',
            'Duration',
            'File Size',
            'Processed',
            'Reviewed',
            'Reviewed By',
            'Review Date',
            'Comments',
        ];

        const rows = sortedAssets.map(asset => [
            asset.assetTitle || '',
            asset.siteName || '',
            asset.siteCountry || '',
            asset.subjectNumber || '',
            asset.studyArm || '',
            asset.studyEvent || '',
            asset.studyProcedure || '',
            asset.studyProcedureDate || '',
            asset.uploadDate
                ? format(
                      typeof asset.uploadDate === 'string'
                          ? parseISO(asset.uploadDate)
                          : asset.uploadDate,
                      'yyyy-MM-dd HH:mm:ss'
                  )
                : '',
            asset.uploadedBy || '',
            asset.assetDuration || '',
            asset.fileSize || '',
            asset.processed || '',
            asset.reviewed ? 'Yes' : 'No',
            asset.reviewedBy || '',
            asset.reviewedDate || '',
            (asset.comments || '').replace(/"/g, '""'),
        ]);

        const csvContent = [
            headers.join(','),
            ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
        ].join('\n');

        const blob = new Blob([csvContent], {
            type: 'text/csv;charset=utf-8;',
        });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);
        const sanitizedTitle = assetListTitle
            .replace(/[^a-zA-Z0-9]/g, '_')
            .substring(0, 50);
        const timestamp = format(new Date(), 'yyyy-MM-dd');

        link.setAttribute('href', url);
        link.setAttribute('download', `${sanitizedTitle}_${timestamp}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, [sortedAssets, assetListTitle]);

    if (!showAssetList) return null;

    return (
        <div
            className="fixed inset-0 bg-black/50 flex items-center justify-center z-[2000] p-4"
            onClick={handleClose}
            role="dialog"
            aria-modal="true"
            aria-labelledby="list-modal-title"
        >
            <div
                className="bg-white rounded-lg w-full max-w-[1000px] max-h-[90vh] flex flex-col shadow-2xl"
                onClick={e => e.stopPropagation()}
            >
                <div className="flex justify-between items-start p-5 border-b border-neutral-200 bg-neutral-50 rounded-t-lg">
                    <div className="flex-1">
                        <h2
                            id="list-modal-title"
                            className="text-lg font-semibold text-neutral-800"
                        >
                            {assetListTitle}
                        </h2>
                        <span className="text-xs text-neutral-500 mt-1 block">
                            {filteredAssets.length} record
                            {filteredAssets.length !== 1 ? 's' : ''}
                        </span>
                    </div>
                    <button
                        className="text-neutral-500 hover:text-neutral-700 text-3xl leading-none ml-4"
                        onClick={handleClose}
                        aria-label="Close"
                    >
                        &times;
                    </button>
                </div>

                <div className="p-4 border-b border-neutral-100 bg-white flex justify-between items-center gap-4">
                    <div className="relative max-w-[300px] flex-1">
                        <input
                            type="text"
                            placeholder="Search assets..."
                            value={searchTerm}
                            onChange={e => setSearchTerm(e.target.value)}
                            className="w-full px-3 py-2 pr-8 border border-neutral-300 rounded-md text-sm focus:outline-none focus:border-chilli-red focus:ring-2 focus:ring-chilli-red/10"
                        />
                        {searchTerm && (
                            <button
                                className="absolute right-2 top-1/2 -translate-y-1/2 text-neutral-400 hover:text-neutral-600 text-xl leading-none"
                                onClick={() => setSearchTerm('')}
                            >
                                &times;
                            </button>
                        )}
                    </div>
                    <button
                        className="px-4 py-2 bg-chilli-red text-white rounded-md text-sm font-medium hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                        onClick={exportToCsv}
                        disabled={sortedAssets.length === 0}
                    >
                        Export CSV
                    </button>
                </div>

                <div className="flex-1 overflow-hidden flex flex-col">
                    {paginatedAssets.length === 0 ? (
                        <div className="flex items-center justify-center p-12 text-neutral-500">
                            No assets found
                            {searchTerm ? ' matching your search' : ''}
                        </div>
                    ) : (
                        <div className="overflow-auto flex-1">
                            <table className="w-full text-sm border-collapse">
                                <thead className="sticky top-0 bg-neutral-50 z-10">
                                    <tr>
                                        <th
                                            className="text-left py-3 px-4 font-semibold text-neutral-600 border-b border-neutral-200 cursor-pointer hover:text-chilli-red whitespace-nowrap"
                                            onClick={() =>
                                                handleSort('assetTitle')
                                            }
                                        >
                                            Asset
                                            {sortField === 'assetTitle' && (
                                                <span className="text-[0.625rem] ml-1">
                                                    {sortDirection === 'asc'
                                                        ? '▲'
                                                        : '▼'}
                                                </span>
                                            )}
                                        </th>
                                        <th
                                            className="text-left py-3 px-4 font-semibold text-neutral-600 border-b border-neutral-200 cursor-pointer hover:text-chilli-red whitespace-nowrap"
                                            onClick={() =>
                                                handleSort('siteName')
                                            }
                                        >
                                            Site
                                            {sortField === 'siteName' && (
                                                <span className="text-[0.625rem] ml-1">
                                                    {sortDirection === 'asc'
                                                        ? '▲'
                                                        : '▼'}
                                                </span>
                                            )}
                                        </th>
                                        <th
                                            className="text-left py-3 px-4 font-semibold text-neutral-600 border-b border-neutral-200 cursor-pointer hover:text-chilli-red whitespace-nowrap"
                                            onClick={() =>
                                                handleSort('subjectNumber')
                                            }
                                        >
                                            Subject
                                            {sortField === 'subjectNumber' && (
                                                <span className="text-[0.625rem] ml-1">
                                                    {sortDirection === 'asc'
                                                        ? '▲'
                                                        : '▼'}
                                                </span>
                                            )}
                                        </th>
                                        <th
                                            className="text-left py-3 px-4 font-semibold text-neutral-600 border-b border-neutral-200 cursor-pointer hover:text-chilli-red whitespace-nowrap"
                                            onClick={() =>
                                                handleSort('uploadDate')
                                            }
                                        >
                                            Upload Date
                                            {sortField === 'uploadDate' && (
                                                <span className="text-[0.625rem] ml-1">
                                                    {sortDirection === 'asc'
                                                        ? '▲'
                                                        : '▼'}
                                                </span>
                                            )}
                                        </th>
                                        <th className="text-left py-3 px-4 font-semibold text-neutral-600 border-b border-neutral-200 whitespace-nowrap">
                                            Status
                                        </th>
                                        <th className="w-[60px] text-center py-3 px-4 font-semibold text-neutral-600 border-b border-neutral-200">
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {paginatedAssets.map(asset => (
                                        <tr
                                            key={asset.assetId}
                                            className="cursor-pointer hover:bg-neutral-50"
                                            onClick={() =>
                                                handleRowClick(asset)
                                            }
                                        >
                                            <td className="py-3 px-4 border-b border-neutral-100 text-neutral-700">
                                                <div className="flex flex-col gap-0.5">
                                                    <span className="font-medium text-neutral-800">
                                                        {asset.assetTitle ||
                                                            '-'}
                                                    </span>
                                                    {asset.studyProcedure && (
                                                        <span className="text-xs text-neutral-500">
                                                            {
                                                                asset.studyProcedure
                                                            }
                                                        </span>
                                                    )}
                                                </div>
                                            </td>
                                            <td className="py-3 px-4 border-b border-neutral-100 text-neutral-700">
                                                {asset.siteName || '-'}
                                            </td>
                                            <td className="py-3 px-4 border-b border-neutral-100 text-neutral-700">
                                                {asset.subjectNumber || '-'}
                                            </td>
                                            <td className="py-3 px-4 border-b border-neutral-100 text-neutral-700">
                                                {formatDate(asset.uploadDate)}
                                            </td>
                                            <td className="py-3 px-4 border-b border-neutral-100">
                                                <span
                                                    className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium ${
                                                        asset.reviewed
                                                            ? 'bg-green-100 text-green-700'
                                                            : 'bg-orange-100 text-orange-700'
                                                    }`}
                                                >
                                                    {asset.reviewed
                                                        ? 'Reviewed'
                                                        : 'Pending'}
                                                </span>
                                            </td>
                                            <td className="w-[60px] text-center py-3 px-4 border-b border-neutral-100">
                                                {asset.assetLink && (
                                                    <button
                                                        className="px-2 py-1 bg-chilli-red text-white rounded text-sm hover:bg-red-700"
                                                        onClick={e =>
                                                            handleViewAsset(
                                                                e,
                                                                asset
                                                            )
                                                        }
                                                        title="View Asset"
                                                    >
                                                        ↗
                                                    </button>
                                                )}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                {totalPages > 1 && (
                    <div className="flex items-center justify-center gap-4 py-3 px-6 border-t border-neutral-100 bg-white">
                        <button
                            className="px-3 py-1.5 bg-white border border-neutral-300 rounded text-xs text-neutral-700 hover:bg-neutral-100 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={currentPage === 1}
                            onClick={() => goToPage(currentPage - 1)}
                        >
                            Previous
                        </button>
                        <span className="text-xs text-neutral-500">
                            Page {currentPage} of {totalPages}
                        </span>
                        <button
                            className="px-3 py-1.5 bg-white border border-neutral-300 rounded text-xs text-neutral-700 hover:bg-neutral-100 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={currentPage === totalPages}
                            onClick={() => goToPage(currentPage + 1)}
                        >
                            Next
                        </button>
                    </div>
                )}

                <div className="flex justify-end gap-3 p-4 border-t border-neutral-200 bg-neutral-50 rounded-b-lg">
                    <button
                        className="px-5 py-2.5 bg-white border border-neutral-300 rounded-md text-sm font-medium text-neutral-700 hover:bg-neutral-100"
                        onClick={handleClose}
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
}

// src/lib/components/AssetListModal.svelte
<script lang="ts">
  import type { AssetRecord } from '../types';
  import { assetModalStore } from '../stores/assetModalStore';
  import { format, parseISO } from 'date-fns';

  export let title: string;
  export let assets: AssetRecord[];

  let searchTerm = '';
  let sortField: keyof AssetRecord = 'uploadDate';
  let sortDirection: 'asc' | 'desc' = 'desc';

  const PAGE_SIZE = 25;
  let currentPage = 1;

  $: filteredAssets = assets.filter(asset => {
    if (!searchTerm) return true;
    const term = searchTerm.toLowerCase();
    return (
      asset.assetTitle?.toLowerCase().includes(term) ||
      asset.siteName?.toLowerCase().includes(term) ||
      asset.subjectNumber?.toLowerCase().includes(term) ||
      asset.uploadedBy?.toLowerCase().includes(term) ||
      asset.studyProcedure?.toLowerCase().includes(term)
    );
  });

  $: sortedAssets = [...filteredAssets].sort((a, b) => {
    const aVal = a[sortField];
    const bVal = b[sortField];

    if (aVal === null || aVal === undefined) return 1;
    if (bVal === null || bVal === undefined) return -1;

    let comparison = 0;
    if (typeof aVal === 'string' && typeof bVal === 'string') {
      comparison = aVal.localeCompare(bVal);
    } else if (aVal instanceof Date && bVal instanceof Date) {
      comparison = aVal.getTime() - bVal.getTime();
    } else {
      comparison = String(aVal).localeCompare(String(bVal));
    }

    return sortDirection === 'asc' ? comparison : -comparison;
  });

  $: totalPages = Math.ceil(sortedAssets.length / PAGE_SIZE);
  $: paginatedAssets = sortedAssets.slice(
    (currentPage - 1) * PAGE_SIZE,
    currentPage * PAGE_SIZE
  );

  $: if (searchTerm) {
    currentPage = 1;
  }

  function formatDate(date: Date | string | null | undefined): string {
    if (!date) return '-';
    try {
      const d = typeof date === 'string' ? parseISO(date) : date;
      return format(d, 'dd/MM/yyyy');
    } catch {
      return '-';
    }
  }

  function handleClose() {
    assetModalStore.closeList();
  }

  function handleRowClick(asset: AssetRecord) {
    assetModalStore.viewAssetFromList(asset);
  }

  function handleViewAsset(event: MouseEvent, asset: AssetRecord) {
    event.stopPropagation();
    if (asset.assetLink) {
      window.open(asset.assetLink, '_blank', 'noopener,noreferrer');
    }
  }

  function handleSort(field: keyof AssetRecord) {
    if (sortField === field) {
      sortDirection = sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      sortField = field;
      sortDirection = 'desc';
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      handleClose();
    }
  }

  function goToPage(page: number) {
    if (page >= 1 && page <= totalPages) {
      currentPage = page;
    }
  }

  function exportToCsv() {
    const headers = [
      'Asset Title',
      'Site Name',
      'Site Country',
      'Subject Number',
      'Study Arm',
      'Study Event',
      'Study Procedure',
      'Procedure Date',
      'Upload Date',
      'Uploaded By',
      'Duration',
      'File Size',
      'Processed',
      'Reviewed',
      'Reviewed By',
      'Review Date',
      'Comments'
    ];

    const rows = sortedAssets.map(asset => [
      asset.assetTitle || '',
      asset.siteName || '',
      asset.siteCountry || '',
      asset.subjectNumber || '',
      asset.studyArm || '',
      asset.studyEvent || '',
      asset.studyProcedure || '',
      asset.studyProcedureDate || '',
      asset.uploadDate ? format(asset.uploadDate, 'yyyy-MM-dd HH:mm:ss') : '',
      asset.uploadedBy || '',
      asset.assetDuration || '',
      asset.fileSize || '',
      asset.processed || '',
      asset.reviewed ? 'Yes' : 'No',
      asset.reviewedBy || '',
      asset.reviewedDate || '',
      (asset.comments || '').replace(/"/g, '""')
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    const sanitizedTitle = title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50);
    const timestamp = format(new Date(), 'yyyy-MM-dd');

    link.setAttribute('href', url);
    link.setAttribute('download', `${sanitizedTitle}_${timestamp}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
</script>

<svelte:window on:keydown={handleKeydown} />

<div class="modal-overlay" on:click={handleClose} on:keydown={handleKeydown} role="dialog" aria-modal="true" aria-labelledby="list-modal-title">
  <div class="modal" on:click|stopPropagation on:keydown|stopPropagation role="document">
    <div class="modal-header">
      <div class="header-content">
        <h2 id="list-modal-title">{title}</h2>
        <span class="record-count">{filteredAssets.length} record{filteredAssets.length !== 1 ? 's' : ''}</span>
      </div>
      <button class="close-btn" on:click={handleClose} aria-label="Close">
        <span>&times;</span>
      </button>
    </div>

    <div class="modal-toolbar">
      <div class="search-box">
        <input
          type="text"
          placeholder="Search assets..."
          bind:value={searchTerm}
          class="search-input"
        />
        {#if searchTerm}
          <button class="clear-search" on:click={() => searchTerm = ''}>
            &times;
          </button>
        {/if}
      </div>
      <button class="btn-export" on:click={exportToCsv} disabled={sortedAssets.length === 0}>
        Export CSV
      </button>
    </div>

    <div class="modal-body">
      {#if paginatedAssets.length === 0}
        <div class="empty-state">
          <p>No assets found{searchTerm ? ' matching your search' : ''}</p>
        </div>
      {:else}
        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th class="sortable" on:click={() => handleSort('assetTitle')}>
                  Asset
                  {#if sortField === 'assetTitle'}
                    <span class="sort-indicator">{sortDirection === 'asc' ? '▲' : '▼'}</span>
                  {/if}
                </th>
                <th class="sortable" on:click={() => handleSort('siteName')}>
                  Site
                  {#if sortField === 'siteName'}
                    <span class="sort-indicator">{sortDirection === 'asc' ? '▲' : '▼'}</span>
                  {/if}
                </th>
                <th class="sortable" on:click={() => handleSort('subjectNumber')}>
                  Subject
                  {#if sortField === 'subjectNumber'}
                    <span class="sort-indicator">{sortDirection === 'asc' ? '▲' : '▼'}</span>
                  {/if}
                </th>
                <th class="sortable" on:click={() => handleSort('uploadDate')}>
                  Upload Date
                  {#if sortField === 'uploadDate'}
                    <span class="sort-indicator">{sortDirection === 'asc' ? '▲' : '▼'}</span>
                  {/if}
                </th>
                <th>Status</th>
                <th class="action-col">Action</th>
              </tr>
            </thead>
            <tbody>
              {#each paginatedAssets as asset}
                <tr class="clickable" on:click={() => handleRowClick(asset)}>
                  <td class="asset-cell">
                    <span class="asset-title">{asset.assetTitle || '-'}</span>
                    {#if asset.studyProcedure}
                      <span class="asset-procedure">{asset.studyProcedure}</span>
                    {/if}
                  </td>
                  <td>{asset.siteName || '-'}</td>
                  <td>{asset.subjectNumber || '-'}</td>
                  <td>{formatDate(asset.uploadDate)}</td>
                  <td>
                    <span class="status-badge" class:reviewed={asset.reviewed} class:pending={!asset.reviewed}>
                      {asset.reviewed ? 'Reviewed' : 'Pending'}
                    </span>
                  </td>
                  <td class="action-col">
                    {#if asset.assetLink}
                      <button
                        class="view-btn"
                        on:click={(e) => handleViewAsset(e, asset)}
                        title="View Asset"
                      >
                        &#8599;
                      </button>
                    {/if}
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </div>

    {#if totalPages > 1}
      <div class="pagination">
        <button
          class="page-btn"
          disabled={currentPage === 1}
          on:click={() => goToPage(currentPage - 1)}
        >
          Previous
        </button>
        <span class="page-info">
          Page {currentPage} of {totalPages}
        </span>
        <button
          class="page-btn"
          disabled={currentPage === totalPages}
          on:click={() => goToPage(currentPage + 1)}
        >
          Next
        </button>
      </div>
    {/if}

    <div class="modal-footer">
      <button class="btn-secondary" on:click={handleClose}>Close</button>
    </div>
  </div>
</div>

<style>
  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 2000;
    padding: 1rem;
  }

  .modal {
    background: var(--white);
    border-radius: 0.5rem;
    width: 100%;
    max-width: 1000px;
    max-height: 90vh;
    display: flex;
    flex-direction: column;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding: 1.25rem 1.5rem;
    border-bottom: 1px solid var(--neutral-200);
    background: var(--neutral-50);
    border-radius: 0.5rem 0.5rem 0 0;
  }

  .header-content {
    flex: 1;
  }

  .modal-header h2 {
    margin: 0;
    font-size: 1.125rem;
    color: var(--neutral-800);
    font-weight: 600;
  }

  .record-count {
    font-size: 0.75rem;
    color: var(--neutral-500);
    margin-top: 0.25rem;
    display: block;
  }

  .close-btn {
    background: none;
    border: none;
    font-size: 1.75rem;
    color: var(--neutral-500);
    cursor: pointer;
    padding: 0;
    line-height: 1;
    margin-left: 1rem;
  }

  .close-btn:hover {
    color: var(--neutral-700);
  }

  .modal-toolbar {
    padding: 1rem 1.5rem;
    border-bottom: 1px solid var(--neutral-100);
    background: var(--white);
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 1rem;
  }

  .search-box {
    position: relative;
    max-width: 300px;
    flex: 1;
  }

  .btn-export {
    padding: 0.5rem 1rem;
    background: var(--chilli-red);
    color: white;
    border: none;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: background 0.2s;
    white-space: nowrap;
  }

  .btn-export:hover:not(:disabled) {
    background: var(--chilli-red-dark);
  }

  .btn-export:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .search-input {
    width: 100%;
    padding: 0.5rem 2rem 0.5rem 0.75rem;
    border: 1px solid var(--neutral-300);
    border-radius: 0.375rem;
    font-size: 0.875rem;
  }

  .search-input:focus {
    outline: none;
    border-color: var(--chilli-red);
    box-shadow: 0 0 0 2px rgba(200, 16, 46, 0.1);
  }

  .clear-search {
    position: absolute;
    right: 0.5rem;
    top: 50%;
    transform: translateY(-50%);
    background: none;
    border: none;
    color: var(--neutral-400);
    cursor: pointer;
    font-size: 1.25rem;
    line-height: 1;
    padding: 0;
  }

  .clear-search:hover {
    color: var(--neutral-600);
  }

  .modal-body {
    flex: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .table-container {
    overflow: auto;
    flex: 1;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
  }

  thead {
    position: sticky;
    top: 0;
    background: var(--neutral-50);
    z-index: 1;
  }

  th {
    text-align: left;
    padding: 0.75rem 1rem;
    font-weight: 600;
    color: var(--neutral-600);
    border-bottom: 1px solid var(--neutral-200);
    white-space: nowrap;
  }

  th.sortable {
    cursor: pointer;
    user-select: none;
  }

  th.sortable:hover {
    color: var(--chilli-red);
  }

  .sort-indicator {
    font-size: 0.625rem;
    margin-left: 0.25rem;
  }

  td {
    padding: 0.75rem 1rem;
    border-bottom: 1px solid var(--neutral-100);
    color: var(--neutral-700);
  }

  tr.clickable {
    cursor: pointer;
  }

  tr.clickable:hover {
    background: var(--neutral-50);
  }

  .asset-cell {
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
  }

  .asset-title {
    font-weight: 500;
    color: var(--neutral-800);
  }

  .asset-procedure {
    font-size: 0.75rem;
    color: var(--neutral-500);
  }

  .action-col {
    width: 60px;
    text-align: center;
  }

  .status-badge {
    display: inline-block;
    padding: 0.125rem 0.5rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 500;
  }

  .status-badge.reviewed {
    background: var(--success-green-light, #dcfce7);
    color: var(--success-green, #16a34a);
  }

  .status-badge.pending {
    background: var(--warning-orange-light, #fef3c7);
    color: var(--warning-orange, #d97706);
  }

  .view-btn {
    background: var(--chilli-red);
    color: white;
    border: none;
    border-radius: 0.25rem;
    padding: 0.375rem 0.5rem;
    font-size: 0.875rem;
    cursor: pointer;
    transition: background 0.2s;
  }

  .view-btn:hover {
    background: var(--chilli-red-dark);
  }

  .empty-state {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 3rem;
    color: var(--neutral-500);
  }

  .pagination {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 1rem;
    padding: 0.75rem 1.5rem;
    border-top: 1px solid var(--neutral-100);
    background: var(--white);
  }

  .page-btn {
    padding: 0.375rem 0.75rem;
    background: var(--white);
    border: 1px solid var(--neutral-300);
    border-radius: 0.25rem;
    font-size: 0.75rem;
    color: var(--neutral-700);
    cursor: pointer;
  }

  .page-btn:hover:not(:disabled) {
    background: var(--neutral-100);
  }

  .page-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .page-info {
    font-size: 0.75rem;
    color: var(--neutral-500);
  }

  .modal-footer {
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
    padding: 1rem 1.5rem;
    border-top: 1px solid var(--neutral-200);
    background: var(--neutral-50);
    border-radius: 0 0 0.5rem 0.5rem;
  }

  .btn-secondary {
    padding: 0.625rem 1.25rem;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
    background: var(--white);
    color: var(--neutral-700);
    border: 1px solid var(--neutral-300);
  }

  .btn-secondary:hover {
    background: var(--neutral-100);
  }

  @media (max-width: 768px) {
    .modal {
      margin: 0.5rem;
      max-height: calc(100vh - 1rem);
    }

    th, td {
      padding: 0.5rem;
    }

    .modal-toolbar {
      padding: 0.75rem 1rem;
    }

    .search-box {
      max-width: 100%;
    }
  }
</style>
