// apps/dashboard/components/Chart.tsx
'use client';

import { useRef, useEffect, useCallback } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler,
  LineController,
  BarController,
  DoughnutController,
  PieController,
  ChartData,
  ChartOptions,
  ChartType
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler,
  LineController,
  BarController,
  DoughnutController,
  PieController
);

ChartJS.defaults.animation = false;

interface ChartProps {
  type: 'line' | 'bar' | 'doughnut' | 'pie';
  data: ChartData<ChartType>;
  options?: ChartOptions;
  height?: string;
  clickable?: boolean;
  onBarClick?: (data: { label: string; index: number; value: number }) => void;
}

export function Chart({
  type,
  data,
  options = {},
  height = '300px',
  clickable = false,
  onBarClick
}: ChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const chartRef = useRef<ChartJS | null>(null);

  const defaultOptions: ChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    animation: false,
    plugins: {
      legend: {
        display: true,
        position: 'top',
      },
      tooltip: {
        mode: 'index',
        intersect: false,
      }
    }
  };

  const handleCanvasClick = useCallback((event: MouseEvent) => {
    if (!clickable || !chartRef.current || !onBarClick) return;

    const elements = chartRef.current.getElementsAtEventForMode(
      event,
      'nearest',
      { intersect: true },
      false
    );

    if (elements.length > 0) {
      const element = elements[0];
      const label = chartRef.current.data.labels?.[element.index] as string;
      const value = chartRef.current.data.datasets[element.datasetIndex].data[element.index] as number;
      onBarClick({ label, index: element.index, value });
    }
  }, [clickable, onBarClick]);

  useEffect(() => {
    if (!canvasRef.current) return;

    if (chartRef.current) {
      chartRef.current.destroy();
    }

    const ctx = canvasRef.current.getContext('2d');
    if (!ctx) return;

    chartRef.current = new ChartJS(ctx, {
      type,
      data,
      options: { ...defaultOptions, ...options }
    });

    return () => {
      if (chartRef.current) {
        chartRef.current.destroy();
      }
    };
  }, [type]);

  useEffect(() => {
    if (chartRef.current && data) {
      chartRef.current.data = data;
      chartRef.current.update('none');
    }
  }, [data]);

  useEffect(() => {
    if (chartRef.current && options) {
      chartRef.current.options = { ...defaultOptions, ...options };
      chartRef.current.update('none');
    }
  }, [options]);

  return (
    <div
      className={`relative w-full ${clickable ? 'cursor-pointer' : ''}`}
      style={{ height }}
    >
      <canvas
        ref={canvasRef}
        onClick={(e) => handleCanvasClick(e.nativeEvent)}
      />
    </div>
  );
}

// src/lib/components/Chart.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import {
    Chart,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    BarElement,
    ArcElement,
    Title,
    Tooltip,
    Legend,
    Filler,
    LineController,
    BarController,
    DoughnutController,
    PieController
  } from 'chart.js';

  Chart.register(
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    BarElement,
    ArcElement,
    Title,
    Tooltip,
    Legend,
    Filler,
    LineController,
    BarController,
    DoughnutController,
    PieController
  );

  Chart.defaults.animation = false;

  export let type: 'line' | 'bar' | 'doughnut' | 'pie';
  export let data: any;
  export let options: any = {};
  export let height: string = '300px';
  export let clickable: boolean = false;

  const dispatch = createEventDispatcher<{ barClick: { label: string; index: number; value: number } }>();

  let canvas: HTMLCanvasElement;
  let chart: Chart;

  const defaultOptions = {
    responsive: true,
    maintainAspectRatio: false,
    animation: false,
    plugins: {
      legend: {
        display: true,
        position: 'top' as const,
      },
      tooltip: {
        mode: 'index',
        intersect: false,
      }
    }
  };

  function handleCanvasClick(event: MouseEvent) {
    if (!clickable || !chart) return;

    const elements = chart.getElementsAtEventForMode(event, 'nearest', { intersect: true }, false);
    if (elements.length > 0) {
      const element = elements[0];
      const label = chart.data.labels?.[element.index] as string;
      const value = chart.data.datasets[element.datasetIndex].data[element.index] as number;
      dispatch('barClick', { label, index: element.index, value });
    }
  }

  onMount(() => {
    if (canvas) {
      chart = new Chart(canvas, {
        type,
        data,
        options: { ...defaultOptions, ...options }
      });
    }
  });

  onDestroy(() => {
    if (chart) {
      chart.destroy();
    }
  });

  $: if (chart && data) {
    chart.data = data;
    chart.update('none');
  }
</script>

<div class="chart-container" class:clickable style="height: {height}">
  <canvas bind:this={canvas} on:click={handleCanvasClick}></canvas>
</div>

<style>
  .chart-container {
    position: relative;
    width: 100%;
  }

  .chart-container.clickable canvas {
    cursor: pointer;
  }
</style>
