// apps/dashboard/components/IntegrationHealth.tsx
'use client';

import { useMemo, useCallback } from 'react';
import { useDashboard } from '../contexts/DashboardContext';
import { WorldMap } from './WorldMap';

function formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
}

function truncate(text: string, length: number): string {
    return text.length > length ? text.substring(0, length) + '...' : text;
}

export function IntegrationHealth() {
    const {
        filteredRecords,
        countryDistribution,
        isLoading,
        setSelectedAsset,
        setShowAssetList,
        setAssetListTitle,
        setAssetListRecords,
    } = useDashboard();

    const evaluatorStats = useMemo(() => {
        const evaluatorCounts = new Map<string, number>();
        filteredRecords.forEach(record => {
            const evaluator = record.evaluator?.trim();
            if (evaluator) {
                evaluatorCounts.set(
                    evaluator,
                    (evaluatorCounts.get(evaluator) || 0) + 1
                );
            }
        });
        return Array.from(evaluatorCounts.entries())
            .map(([name, count]) => ({ name, count }))
            .sort((a, b) => b.count - a.count);
    }, [filteredRecords]);

    const recentActivity = useMemo(() => {
        return [...filteredRecords]
            .sort((a, b) => b.uploadDate.getTime() - a.uploadDate.getTime())
            .slice(0, 10);
    }, [filteredRecords]);

    const processedCount = useMemo(
        () => filteredRecords.filter(r => r.processed === 'Yes').length,
        [filteredRecords]
    );

    const reviewedCount = useMemo(
        () => filteredRecords.filter(r => r.reviewed).length,
        [filteredRecords]
    );

    const handleActivityClick = useCallback(
        (asset: (typeof filteredRecords)[0]) => {
            setSelectedAsset(asset);
        },
        [setSelectedAsset]
    );

    const handleViewAsset = useCallback(
        (event: React.MouseEvent, asset: (typeof filteredRecords)[0]) => {
            event.stopPropagation();
            if (asset.assetLink) {
                window.open(asset.assetLink, '_blank', 'noopener,noreferrer');
            }
        },
        []
    );

    const handleEvaluatorClick = useCallback(
        (evaluatorName: string) => {
            const evaluatorAssets = filteredRecords.filter(
                r => r.evaluator === evaluatorName
            );
            setAssetListTitle(`Assets Evaluated by: ${evaluatorName}`);
            setAssetListRecords(evaluatorAssets);
            setShowAssetList(true);
        },
        [
            filteredRecords,
            setAssetListTitle,
            setAssetListRecords,
            setShowAssetList,
        ]
    );

    const handleCountryClick = useCallback(
        (country: string) => {
            const countryAssets = filteredRecords.filter(
                r => r.siteCountry === country
            );
            setAssetListTitle(`Assets from: ${country}`);
            setAssetListRecords(countryAssets);
            setShowAssetList(true);
        },
        [
            filteredRecords,
            setAssetListTitle,
            setAssetListRecords,
            setShowAssetList,
        ]
    );

    const maxEvaluatorCount =
        evaluatorStats.length > 0 ? evaluatorStats[0].count : 1;

    if (isLoading) {
        return (
            <div className="flex flex-col gap-6">
                <div className="animate-pulse">
                    <div className="h-8 bg-neutral-200 rounded w-64 mb-2"></div>
                    <div className="h-4 bg-neutral-200 rounded w-80"></div>
                </div>
                <div className="bg-white rounded-lg shadow-sm p-6 h-[500px] animate-pulse">
                    <div className="h-full bg-neutral-100 rounded"></div>
                </div>
            </div>
        );
    }

    return (
        <div className="flex flex-col gap-6">
            <div className="mb-2">
                <h2 className="text-xl font-semibold text-neutral-800 mb-1">
                    Integration Health & Activity
                </h2>
                <p className="text-neutral-500 text-sm">
                    System usage, evaluator activity, and geographic
                    distribution
                </p>
            </div>

            <div className="bg-white rounded-lg shadow-sm p-6">
                <h3 className="text-lg font-semibold text-neutral-800 mb-4">
                    Geographic Distribution
                </h3>
                <WorldMap
                    countryData={countryDistribution}
                    onCountryClick={handleCountryClick}
                />
            </div>

            <div className="bg-white rounded-lg shadow-sm p-6">
                <h3 className="text-lg font-semibold text-neutral-800 mb-4">
                    Top Evaluators
                </h3>
                <div className="flex flex-col gap-2">
                    {evaluatorStats.slice(0, 10).map(evaluator => (
                        <div
                            key={evaluator.name}
                            className="flex items-center gap-3 px-3 py-2 bg-neutral-50 rounded-md border border-neutral-200 cursor-pointer transition-all hover:bg-neutral-100 hover:border-chilli-red"
                            onClick={() => handleEvaluatorClick(evaluator.name)}
                            onKeyDown={e =>
                                e.key === 'Enter' &&
                                handleEvaluatorClick(evaluator.name)
                            }
                            tabIndex={0}
                            role="button"
                        >
                            <span className="text-sm text-neutral-700 min-w-[150px] flex-shrink-0">
                                {evaluator.name}
                            </span>
                            <div className="flex-1 h-2 bg-neutral-200 rounded overflow-hidden">
                                <div
                                    className="h-full bg-chilli-red rounded transition-all duration-300"
                                    style={{
                                        width: `${(evaluator.count / maxEvaluatorCount) * 100}%`,
                                    }}
                                />
                            </div>
                            <span className="text-sm font-semibold text-neutral-600 min-w-[40px] text-right">
                                {evaluator.count}
                            </span>
                        </div>
                    ))}
                </div>
            </div>

            <div className="bg-white rounded-lg shadow-sm p-6">
                <h3 className="text-lg font-semibold text-neutral-800 mb-4">
                    Recent Upload Activity
                </h3>
                <div className="flex flex-col gap-3">
                    {recentActivity.map(activity => (
                        <div
                            key={activity.assetId}
                            className="flex items-center gap-4 p-3 bg-neutral-50 rounded-md border border-neutral-200 cursor-pointer transition-all hover:bg-neutral-100 hover:border-chilli-red"
                            onClick={() => handleActivityClick(activity)}
                            onKeyDown={e =>
                                e.key === 'Enter' &&
                                handleActivityClick(activity)
                            }
                            tabIndex={0}
                            role="button"
                        >
                            <div className="text-2xl">📹</div>
                            <div className="flex-1 min-w-0">
                                <div className="font-medium text-neutral-900 text-sm">
                                    {truncate(activity.assetTitle, 40)}
                                </div>
                                <div className="flex gap-4 flex-wrap mt-1 text-xs text-neutral-600">
                                    <span>
                                        <strong>Site:</strong>{' '}
                                        {truncate(activity.siteName, 25)}
                                    </span>
                                    <span>
                                        <strong>Subject:</strong>{' '}
                                        {activity.subjectNumber}
                                    </span>
                                    <span>
                                        <strong>Uploaded by:</strong>{' '}
                                        {activity.uploadedBy}
                                    </span>
                                </div>
                            </div>
                            <div className="text-xs text-neutral-500 whitespace-nowrap">
                                {formatDate(activity.uploadDate)}
                            </div>
                            <div className="whitespace-nowrap">
                                {activity.reviewed ? (
                                    <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full">
                                        Reviewed
                                    </span>
                                ) : (
                                    <span className="px-2 py-1 bg-orange-100 text-orange-700 text-xs font-medium rounded-full">
                                        Pending
                                    </span>
                                )}
                            </div>
                            {activity.assetLink && (
                                <button
                                    className="px-2 py-1 bg-chilli-red text-white text-sm rounded hover:bg-red-700 transition-colors flex-shrink-0"
                                    onClick={e => handleViewAsset(e, activity)}
                                    title="View Asset"
                                >
                                    ↗
                                </button>
                            )}
                        </div>
                    ))}
                </div>
            </div>

            <div className="bg-white rounded-lg shadow-sm p-6">
                <h3 className="text-lg font-semibold text-neutral-800 mb-4">
                    🔗 EDC Integration Status
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="flex items-center gap-3 p-4 bg-neutral-50 rounded-md border border-neutral-200">
                        <div className="w-3 h-3 rounded-full bg-green-500 shadow-[0_0_0_3px_rgba(16,185,129,0.2)] flex-shrink-0" />
                        <div className="flex-1">
                            <div className="font-semibold text-sm text-neutral-900">
                                Upload Service
                            </div>
                            <div className="text-xs text-neutral-600 mt-0.5">
                                Active - Processing videos
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-3 p-4 bg-neutral-50 rounded-md border border-neutral-200">
                        <div className="w-3 h-3 rounded-full bg-green-500 shadow-[0_0_0_3px_rgba(16,185,129,0.2)] flex-shrink-0" />
                        <div className="flex-1">
                            <div className="font-semibold text-sm text-neutral-900">
                                De-identification Engine
                            </div>
                            <div className="text-xs text-neutral-600 mt-0.5">
                                Operational - {processedCount} processed
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-3 p-4 bg-neutral-50 rounded-md border border-neutral-200">
                        <div className="w-3 h-3 rounded-full bg-green-500 shadow-[0_0_0_3px_rgba(16,185,129,0.2)] flex-shrink-0" />
                        <div className="flex-1">
                            <div className="font-semibold text-sm text-neutral-900">
                                Review Workflow
                            </div>
                            <div className="text-xs text-neutral-600 mt-0.5">
                                Active - {reviewedCount} reviews completed
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-3 p-4 bg-neutral-50 rounded-md border border-neutral-200">
                        <div className="w-3 h-3 rounded-full bg-green-500 shadow-[0_0_0_3px_rgba(16,185,129,0.2)] flex-shrink-0" />
                        <div className="flex-1">
                            <div className="font-semibold text-sm text-neutral-900">
                                Data Export API
                            </div>
                            <div className="text-xs text-neutral-600 mt-0.5">
                                Connected - Real-time sync
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/lib/components/IntegrationHealth.svelte
<script lang="ts">
  import Chart from './Chart.svelte';
  import WorldMap from './WorldMap.svelte';
  import type { AssetRecord } from '../types';
  import { assetModalStore } from '../stores/assetModalStore';

  export let records: AssetRecord[];
  export let evaluatorStats: Array<{ name: string; count: number }>;
  export let countryDistribution: Array<{ country: string; count: number }>;

  $: recentActivity = records
    .sort((a, b) => b.uploadDate.getTime() - a.uploadDate.getTime())
    .slice(0, 10);

  $: evaluatorChartData = {
    labels: evaluatorStats.map(e => e.name.substring(0, 20)),
    datasets: [{
      label: 'Assets Evaluated',
      data: evaluatorStats.map(e => e.count),
      backgroundColor: [
        'rgba(200, 16, 46, 0.8)',
        'rgba(16, 185, 129, 0.8)',
        'rgba(237, 118, 33, 0.8)',
        'rgba(118, 15, 108, 0.8)',
        'rgba(175, 26, 98, 0.8)',
        'rgba(155, 10, 33, 0.8)',
        'rgba(200, 16, 46, 0.6)',
        'rgba(237, 118, 33, 0.6)',
        'rgba(118, 15, 108, 0.6)',
        'rgba(175, 26, 98, 0.6)',
      ]
    }]
  };

  function formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  function truncate(text: string, length: number): string {
    return text.length > length ? text.substring(0, length) + '...' : text;
  }

  function handleActivityClick(asset: AssetRecord) {
    assetModalStore.openAssetDetail(asset);
  }

  function handleViewAsset(event: MouseEvent, asset: AssetRecord) {
    event.stopPropagation();
    if (asset.assetLink) {
      window.open(asset.assetLink, '_blank', 'noopener,noreferrer');
    }
  }

  function handleEvaluatorClick(evaluatorName: string) {
    const evaluatorAssets = records.filter(r => r.evaluator === evaluatorName);
    assetModalStore.openAssetList(`Assets Evaluated by: ${evaluatorName}`, evaluatorAssets);
  }

  function handleCountryClick(country: string) {
    const countryAssets = records.filter(r => r.siteCountry === country);
    assetModalStore.openAssetList(`Assets from: ${country}`, countryAssets);
  }
</script>

<div class="integration-health">
  <div class="section-header">
    <h2>Integration Health & Activity</h2>
    <p class="section-subtitle">System usage, evaluator activity, and geographic distribution</p>
  </div>

  <div class="card">
    <h3>Geographic Distribution</h3>
    <WorldMap countryData={countryDistribution} on:countryClick={(e) => handleCountryClick(e.detail)} />
  </div>

  <div class="card">
    <h3>Top Evaluators</h3>
    <div class="evaluator-list">
      {#each evaluatorStats.slice(0, 10) as evaluator}
        <div class="evaluator-item clickable" on:click={() => handleEvaluatorClick(evaluator.name)} on:keydown={(e) => e.key === 'Enter' && handleEvaluatorClick(evaluator.name)} role="button" tabindex="0">
          <span class="evaluator-name">{evaluator.name}</span>
          <div class="evaluator-bar-container">
            <div class="evaluator-bar" style="width: {(evaluator.count / evaluatorStats[0].count) * 100}%"></div>
          </div>
          <span class="evaluator-count">{evaluator.count}</span>
        </div>
      {/each}
    </div>
  </div>

  <div class="card">
    <h3>Recent Upload Activity</h3>
    <div class="activity-list">
      {#each recentActivity as activity}
        <div class="activity-item clickable" on:click={() => handleActivityClick(activity)} on:keydown={(e) => e.key === 'Enter' && handleActivityClick(activity)} role="button" tabindex="0">
          <div class="activity-icon">📹</div>
          <div class="activity-content">
            <div class="activity-title">
              {truncate(activity.assetTitle, 40)}
            </div>
            <div class="activity-meta">
              <span class="meta-item">
                <strong>Site:</strong> {truncate(activity.siteName, 25)}
              </span>
              <span class="meta-item">
                <strong>Subject:</strong> {activity.subjectNumber}
              </span>
              <span class="meta-item">
                <strong>Uploaded by:</strong> {activity.uploadedBy}
              </span>
            </div>
          </div>
          <div class="activity-time">
            {formatDate(activity.uploadDate)}
          </div>
          <div class="activity-status">
            {#if activity.reviewed}
              <span class="badge badge-success">Reviewed</span>
            {:else}
              <span class="badge badge-warning">Pending</span>
            {/if}
          </div>
          {#if activity.assetLink}
            <button class="view-asset-btn" on:click={(e) => handleViewAsset(e, activity)} title="View Asset">
              &#8599;
            </button>
          {/if}
        </div>
      {/each}
    </div>
  </div>

  <div class="card system-status">
    <h3>🔗 EDC Integration Status</h3>
    <div class="status-grid">
      <div class="status-item">
        <div class="status-indicator active"></div>
        <div class="status-details">
          <div class="status-name">Upload Service</div>
          <div class="status-description">Active - Processing videos</div>
        </div>
      </div>
      <div class="status-item">
        <div class="status-indicator active"></div>
        <div class="status-details">
          <div class="status-name">De-identification Engine</div>
          <div class="status-description">Operational - {records.filter(r => r.processed === 'Yes').length} processed</div>
        </div>
      </div>
      <div class="status-item">
        <div class="status-indicator active"></div>
        <div class="status-details">
          <div class="status-name">Review Workflow</div>
          <div class="status-description">Active - {records.filter(r => r.reviewed).length} reviews completed</div>
        </div>
      </div>
      <div class="status-item">
        <div class="status-indicator active"></div>
        <div class="status-details">
          <div class="status-name">Data Export API</div>
          <div class="status-description">Connected - Real-time sync</div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .integration-health {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .section-header {
    margin-bottom: 0.5rem;
  }

  .section-header h2 {
    margin-bottom: 0.25rem;
  }

  .section-subtitle {
    color: var(--neutral-500);
    font-size: 0.875rem;
  }

  .activity-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    margin-top: 1rem;
  }

  .activity-item {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 0.75rem;
    background-color: var(--neutral-50);
    border-radius: 0.375rem;
    border: 1px solid var(--neutral-200);
  }

  .activity-item.clickable {
    cursor: pointer;
    transition: all 0.15s ease;
  }

  .activity-item.clickable:hover {
    background-color: var(--neutral-100);
    border-color: var(--chilli-red);
  }

  .view-asset-btn {
    background: var(--chilli-red);
    color: white;
    border: none;
    border-radius: 0.25rem;
    padding: 0.375rem 0.5rem;
    font-size: 0.875rem;
    cursor: pointer;
    transition: background 0.2s;
    flex-shrink: 0;
  }

  .view-asset-btn:hover {
    background: var(--chilli-red-dark);
  }

  .evaluator-list {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    margin-top: 1rem;
  }

  .evaluator-item {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.5rem 0.75rem;
    background-color: var(--neutral-50);
    border-radius: 0.375rem;
    border: 1px solid var(--neutral-200);
  }

  .evaluator-item.clickable {
    cursor: pointer;
    transition: all 0.15s ease;
  }

  .evaluator-item.clickable:hover {
    background-color: var(--neutral-100);
    border-color: var(--chilli-red);
  }

  .evaluator-name {
    font-size: 0.875rem;
    color: var(--neutral-700);
    min-width: 150px;
    flex-shrink: 0;
  }

  .evaluator-bar-container {
    flex: 1;
    height: 8px;
    background: var(--neutral-200);
    border-radius: 4px;
    overflow: hidden;
  }

  .evaluator-bar {
    height: 100%;
    background: var(--chilli-red);
    border-radius: 4px;
    transition: width 0.3s ease;
  }

  .evaluator-count {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--neutral-600);
    min-width: 40px;
    text-align: right;
  }

  .activity-icon {
    font-size: 1.5rem;
  }

  .activity-content {
    flex: 1;
    min-width: 0;
  }

  .activity-title {
    font-weight: 500;
    color: var(--neutral-900);
    font-size: 0.875rem;
  }

  .activity-meta {
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
    margin-top: 0.25rem;
    font-size: 0.75rem;
    color: var(--neutral-600);
  }

  .meta-item {
    white-space: nowrap;
  }

  .activity-time {
    font-size: 0.75rem;
    color: var(--neutral-500);
    white-space: nowrap;
  }

  .activity-status {
    white-space: nowrap;
  }

  .system-status h3 {
    margin-bottom: 1rem;
  }

  .status-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 1rem;
  }

  .status-item {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem;
    background-color: var(--neutral-50);
    border-radius: 0.375rem;
    border: 1px solid var(--neutral-200);
  }

  .status-indicator {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    flex-shrink: 0;
  }

  .status-indicator.active {
    background-color: var(--success-green);
    box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.2);
  }

  .status-indicator.warning {
    background-color: var(--warning-orange);
    box-shadow: 0 0 0 3px rgba(245, 158, 11, 0.2);
  }

  .status-indicator.error {
    background-color: var(--danger-red);
    box-shadow: 0 0 0 3px rgba(239, 68, 68, 0.2);
  }

  .status-details {
    flex: 1;
  }

  .status-name {
    font-weight: 600;
    font-size: 0.875rem;
    color: var(--neutral-900);
  }

  .status-description {
    font-size: 0.75rem;
    color: var(--neutral-600);
    margin-top: 0.125rem;
  }

  @media (max-width: 768px) {
    .status-grid {
      grid-template-columns: 1fr;
    }
  }
</style>
