// libs/ui/src/components/metric-card.tsx
'use client';

import { ReactNode } from 'react';
import { Card } from './card';

export interface MetricCardProps {
  title: string;
  value: string | number;
  subtitle?: string;
  icon?: ReactNode;
  trend?: {
    value: number;
    isPositive: boolean;
  };
  className?: string;
}

export function MetricCard({
  title,
  value,
  subtitle,
  icon,
  trend,
  className = '',
}: MetricCardProps) {
  return (
    <Card className={`p-6 ${className}`}>
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <p className="text-sm font-medium text-neutral-500">{title}</p>
          <div className="mt-2 flex items-baseline">
            <p className="text-2xl font-semibold text-neutral-900">{value}</p>
            {trend && (
              <span
                className={`ml-2 flex items-center text-sm font-medium ${
                  trend.isPositive ? 'text-success' : 'text-error'
                }`}
              >
                {trend.isPositive ? (
                  <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                    <path
                      fillRule="evenodd"
                      d="M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                ) : (
                  <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                    <path
                      fillRule="evenodd"
                      d="M14.707 10.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 12.586V5a1 1 0 012 0v7.586l2.293-2.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                )}
                {Math.abs(trend.value)}%
              </span>
            )}
          </div>
          {subtitle && <p className="mt-1 text-sm text-neutral-500">{subtitle}</p>}
        </div>
        {icon && (
          <div className="ml-4 flex h-12 w-12 items-center justify-center rounded-lg bg-chilli-red/10 text-chilli-red">
            {icon}
          </div>
        )}
      </div>
    </Card>
  );
}

// src/lib/components/MetricCard.svelte
<script lang="ts">
  export let title: string;
  export let value: string | number;
  export let subtitle: string = '';
  export let trend: number | null = null;
  export let icon: string = '';
</script>

<div class="metric-card card">
  <div class="metric-header">
    <h3 class="metric-title">{title}</h3>
    {#if icon}
      <span class="metric-icon">{icon}</span>
    {/if}
  </div>
  <div class="metric-value">{value}</div>
  {#if subtitle}
    <div class="metric-subtitle">{subtitle}</div>
  {/if}
  {#if trend !== null}
    <div class="metric-trend" class:positive={trend > 0} class:negative={trend < 0}>
      {trend > 0 ? '↑' : '↓'} {Math.abs(trend).toFixed(1)}%
    </div>
  {/if}
</div>

<style>
  .metric-card {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .metric-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }

  .metric-title {
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--neutral-600);
    margin: 0;
  }

  .metric-icon {
    font-size: 1.5rem;
    opacity: 0.5;
  }

  .metric-value {
    font-size: 2rem;
    font-weight: 700;
    color: var(--chilli-red);
    line-height: 1;
  }

  .metric-subtitle {
    font-size: 0.75rem;
    color: var(--neutral-500);
  }

  .metric-trend {
    font-size: 0.875rem;
    font-weight: 600;
  }

  .metric-trend.positive {
    color: var(--success-green);
  }

  .metric-trend.negative {
    color: var(--danger-red);
  }
</style>
