// apps/dashboard/components/WorldMap.tsx
'use client';

import { useEffect, useState, useMemo, useCallback, useRef } from 'react';
import dynamic from 'next/dynamic';
import { resolveAllCoordinates, getCountryCoordinates } from '@cp/data-processing';

interface CountryData {
  country: string;
  count: number;
}

interface WorldMapProps {
  countryData: CountryData[];
  onCountryClick?: (country: string) => void;
}

const MapContainerWithNoSSR = dynamic(
  () => import('react-leaflet').then(mod => mod.MapContainer),
  { ssr: false }
);

const TileLayerWithNoSSR = dynamic(
  () => import('react-leaflet').then(mod => mod.TileLayer),
  { ssr: false }
);

const MarkerWithNoSSR = dynamic(
  () => import('react-leaflet').then(mod => mod.Marker),
  { ssr: false }
);

const PopupWithNoSSR = dynamic(
  () => import('react-leaflet').then(mod => mod.Popup),
  { ssr: false }
);

function MapMarker({
  country,
  count,
  coords,
  maxCount,
  onClick
}: {
  country: string;
  count: number;
  coords: { lat: number; lng: number };
  maxCount: number;
  onClick?: () => void;
}) {
  const [L, setL] = useState<typeof import('leaflet') | null>(null);

  useEffect(() => {
    import('leaflet').then(setL);
  }, []);

  const icon = useMemo(() => {
    if (!L) return undefined;

    const minSize = 24;
    const maxSize = 48;
    const ratio = count / maxCount;
    const size = minSize + ratio * (maxSize - minSize);
    const intensity = Math.min(count / maxCount, 1);
    const opacity = 0.6 + intensity * 0.4;

    return L.divIcon({
      className: 'custom-marker',
      html: `
        <div style="
          width: ${size}px;
          height: ${size}px;
          background: rgba(200, 16, 46, ${opacity});
          border: 2px solid rgba(200, 16, 46, 1);
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          font-weight: 600;
          font-size: ${size > 32 ? '12px' : '10px'};
          box-shadow: 0 2px 8px rgba(0,0,0,0.3);
          cursor: pointer;
          transition: transform 0.2s;
        ">
          ${count}
        </div>
      `,
      iconSize: [size, size],
      iconAnchor: [size / 2, size / 2]
    });
  }, [L, count, maxCount]);

  if (!L || !icon) return null;

  return (
    <MarkerWithNoSSR
      position={[coords.lat, coords.lng]}
      icon={icon}
      eventHandlers={{
        click: () => onClick?.()
      }}
    >
      <PopupWithNoSSR>
        <div style={{ textAlign: 'center', padding: '4px' }}>
          <strong style={{ fontSize: '14px', color: '#1f2937' }}>{country}</strong>
          <br />
          <span style={{ fontSize: '18px', fontWeight: 700, color: '#c8102e' }}>
            {count.toLocaleString()}
          </span>
          <br />
          <span style={{ fontSize: '11px', color: '#6b7280' }}>records</span>
        </div>
      </PopupWithNoSSR>
    </MarkerWithNoSSR>
  );
}

export function WorldMap({ countryData, onCountryClick }: WorldMapProps) {
  const [isLoading, setIsLoading] = useState(true);
  const [coordinatesResolved, setCoordinatesResolved] = useState(false);
  const [mounted, setMounted] = useState(false);
  const prevCountryDataRef = useRef<string>('');

  useEffect(() => {
    setMounted(true);
    import('leaflet/dist/leaflet.css');
  }, []);

  useEffect(() => {
    const currentDataString = JSON.stringify(countryData.map(c => c.country));
    if (currentDataString === prevCountryDataRef.current) return;
    prevCountryDataRef.current = currentDataString;

    async function loadCoordinates() {
      if (countryData.length === 0) {
        setIsLoading(false);
        return;
      }

      setIsLoading(true);
      const countries = countryData.map(c => c.country);
      await resolveAllCoordinates(countries);
      setCoordinatesResolved(true);
      setIsLoading(false);
    }

    loadCoordinates();
  }, [countryData]);

  const maxCount = useMemo(
    () => Math.max(...countryData.map(c => c.count), 1),
    [countryData]
  );

  const totalRecords = useMemo(
    () => countryData.reduce((sum, c) => sum + c.count, 0),
    [countryData]
  );

  const activeCountries = countryData.length;

  const mappedCountries = useMemo(() => {
    if (!coordinatesResolved) return [];
    return countryData.filter(c => getCountryCoordinates(c.country) !== null);
  }, [countryData, coordinatesResolved]);

  const unmappedCountries = useMemo(() => {
    if (!coordinatesResolved) return [];
    return countryData.filter(c => getCountryCoordinates(c.country) === null);
  }, [countryData, coordinatesResolved]);

  const handleCountryClick = useCallback(
    (country: string) => {
      onCountryClick?.(country);
    },
    [onCountryClick]
  );

  if (!mounted) {
    return (
      <div className="flex flex-col gap-4">
        <div className="h-[400px] bg-neutral-100 rounded-lg animate-pulse" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-end gap-6">
        <div className="flex flex-col items-center px-4 py-2 bg-neutral-50 rounded-md">
          <span className="text-xl font-bold text-chilli-red">{activeCountries}</span>
          <span className="text-[0.7rem] text-neutral-500 uppercase tracking-wide">Countries</span>
        </div>
        <div className="flex flex-col items-center px-4 py-2 bg-neutral-50 rounded-md">
          <span className="text-xl font-bold text-chilli-red">{totalRecords.toLocaleString()}</span>
          <span className="text-[0.7rem] text-neutral-500 uppercase tracking-wide">Total Records</span>
        </div>
      </div>

      <div className="relative w-full h-[400px] rounded-lg overflow-hidden border border-neutral-200">
        {isLoading && (
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-white/90 z-[1000] gap-2">
            <div className="w-6 h-6 border-3 border-neutral-200 border-t-chilli-red rounded-full animate-spin" />
            <span className="text-sm text-neutral-600">Loading locations...</span>
          </div>
        )}
        <MapContainerWithNoSSR
          center={[20, 0]}
          zoom={2}
          scrollWheelZoom={true}
          style={{ height: '100%', width: '100%' }}
        >
          <TileLayerWithNoSSR
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
            url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"
          />
          {coordinatesResolved &&
            mappedCountries.map(({ country, count }) => {
              const coords = getCountryCoordinates(country);
              if (!coords) return null;
              return (
                <MapMarker
                  key={country}
                  country={country}
                  count={count}
                  coords={coords}
                  maxCount={maxCount}
                  onClick={() => handleCountryClick(country)}
                />
              );
            })}
        </MapContainerWithNoSSR>
      </div>

      <div className="grid grid-cols-2 gap-2 max-h-[200px] overflow-y-auto pr-2">
        {countryData.map(({ country, count }) => {
          const isUnmapped = coordinatesResolved && getCountryCoordinates(country) === null;
          return (
            <div
              key={country}
              className={`flex items-center gap-2 px-2 py-1.5 bg-neutral-50 rounded ${isUnmapped ? 'opacity-70' : ''}`}
            >
              <span className="text-xs text-neutral-700 min-w-[100px] flex-shrink-0">
                {country}
                {isUnmapped && (
                  <span className="text-orange-500 font-bold ml-1" title="Location not mapped">*</span>
                )}
              </span>
              <div className="flex-1 h-1.5 bg-neutral-200 rounded overflow-hidden">
                <div
                  className="h-full bg-chilli-red rounded transition-all duration-300"
                  style={{ width: `${(count / maxCount) * 100}%` }}
                />
              </div>
              <span className="text-xs font-semibold text-neutral-600 min-w-[40px] text-right">
                {count.toLocaleString()}
              </span>
            </div>
          );
        })}
      </div>

      {coordinatesResolved && unmappedCountries.length > 0 && (
        <div className="text-[0.7rem] text-neutral-500 italic text-center">
          * {unmappedCountries.length} location{unmappedCountries.length > 1 ? 's' : ''} not shown on map
        </div>
      )}
    </div>
  );
}

// src/lib/components/WorldMap.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import L from 'leaflet';
  import 'leaflet/dist/leaflet.css';
  import { resolveAllCoordinates, getCountryCoordinates } from '../utils/countryCoordinates';

  export let countryData: Array<{ country: string; count: number }> = [];

  let mapContainer: HTMLDivElement;
  let map: L.Map | null = null;
  let markersLayer: L.LayerGroup | null = null;
  let coordinatesResolved = false;
  let isLoading = true;

  $: maxCount = Math.max(...countryData.map(c => c.count), 1);
  $: totalRecords = countryData.reduce((sum, c) => sum + c.count, 0);
  $: activeCountries = countryData.length;
  $: mappedCountries = coordinatesResolved
    ? countryData.filter(c => getCountryCoordinates(c.country) !== null)
    : [];
  $: unmappedCountries = coordinatesResolved
    ? countryData.filter(c => getCountryCoordinates(c.country) === null)
    : [];

  function getMarkerSize(count: number): number {
    const minSize = 24;
    const maxSize = 48;
    const ratio = count / maxCount;
    return minSize + ratio * (maxSize - minSize);
  }

  function createMarkerIcon(count: number): L.DivIcon {
    const size = getMarkerSize(count);
    const intensity = Math.min(count / maxCount, 1);
    const opacity = 0.6 + intensity * 0.4;

    return L.divIcon({
      className: 'custom-marker',
      html: `
        <div class="marker-container" style="
          width: ${size}px;
          height: ${size}px;
          background: rgba(200, 16, 46, ${opacity});
          border: 2px solid rgba(200, 16, 46, 1);
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          font-weight: 600;
          font-size: ${size > 32 ? '12px' : '10px'};
          box-shadow: 0 2px 8px rgba(0,0,0,0.3);
          cursor: pointer;
          transition: transform 0.2s;
        ">
          ${count}
        </div>
      `,
      iconSize: [size, size],
      iconAnchor: [size / 2, size / 2]
    });
  }

  function updateMarkers() {
    if (!map || !markersLayer || !coordinatesResolved) return;

    markersLayer.clearLayers();

    countryData.forEach(({ country, count }) => {
      const coords = getCountryCoordinates(country);
      if (coords) {
        const marker = L.marker([coords.lat, coords.lng], {
          icon: createMarkerIcon(count)
        });

        marker.bindPopup(`
          <div style="text-align: center; padding: 4px;">
            <strong style="font-size: 14px; color: #1f2937;">${country}</strong><br/>
            <span style="font-size: 18px; font-weight: 700; color: #c8102e;">${count.toLocaleString()}</span><br/>
            <span style="font-size: 11px; color: #6b7280;">records</span>
          </div>
        `, {
          closeButton: false,
          className: 'custom-popup'
        });

        marker.on('mouseover', function() {
          this.openPopup();
        });
        marker.on('mouseout', function() {
          this.closePopup();
        });

        markersLayer.addLayer(marker);
      }
    });

    const mappedData = countryData.filter(c => getCountryCoordinates(c.country) !== null);
    if (mappedData.length > 0 && map) {
      const bounds = mappedData
        .map(c => getCountryCoordinates(c.country))
        .filter((c): c is { lat: number; lng: number } => c !== null)
        .map(c => [c.lat, c.lng] as L.LatLngTuple);

      if (bounds.length > 0) {
        map.fitBounds(bounds, { padding: [50, 50], maxZoom: 4 });
      }
    }
  }

  function handleResize() {
    if (map) {
      setTimeout(() => {
        map?.invalidateSize();
      }, 100);
    }
  }

  async function loadCoordinates() {
    if (countryData.length === 0) {
      isLoading = false;
      return;
    }

    const countries = countryData.map(c => c.country);
    await resolveAllCoordinates(countries);
    coordinatesResolved = true;
    isLoading = false;
    updateMarkers();
  }

  onMount(() => {
    if (!mapContainer) return;

    map = L.map(mapContainer, {
      center: [20, 0],
      zoom: 2,
      minZoom: 1,
      maxZoom: 6,
      scrollWheelZoom: true,
      zoomControl: true
    });

    L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
      subdomains: 'abcd',
      maxZoom: 19
    }).addTo(map);

    markersLayer = L.layerGroup().addTo(map);

    loadCoordinates();

    window.addEventListener('resize', handleResize);
  });

  onDestroy(() => {
    window.removeEventListener('resize', handleResize);
    if (map) {
      map.remove();
      map = null;
    }
  });

  $: if (map && markersLayer && countryData && countryData.length > 0) {
    coordinatesResolved = false;
    isLoading = true;
    loadCoordinates();
  }
</script>

<div class="world-map">
  <div class="map-header">
    <div class="map-stats">
      <div class="stat">
        <span class="stat-value">{activeCountries}</span>
        <span class="stat-label">Countries</span>
      </div>
      <div class="stat">
        <span class="stat-value">{totalRecords.toLocaleString()}</span>
        <span class="stat-label">Total Records</span>
      </div>
    </div>
  </div>

  <div class="map-container" bind:this={mapContainer}>
    {#if isLoading}
      <div class="map-loading">
        <span class="loading-spinner"></span>
        <span>Loading locations...</span>
      </div>
    {/if}
  </div>

  <div class="country-list">
    {#each countryData as { country, count }}
      <div class="country-item" class:unmapped={coordinatesResolved && !getCountryCoordinates(country)}>
        <span class="country-name">
          {country}
          {#if coordinatesResolved && !getCountryCoordinates(country)}
            <span class="unmapped-indicator" title="Location not mapped">*</span>
          {/if}
        </span>
        <div class="country-bar-container">
          <div
            class="country-bar"
            style="width: {(count / maxCount) * 100}%"
          ></div>
        </div>
        <span class="country-count">{count.toLocaleString()}</span>
      </div>
    {/each}
  </div>

  {#if coordinatesResolved && unmappedCountries.length > 0}
    <div class="unmapped-note">
      * {unmappedCountries.length} location{unmappedCountries.length > 1 ? 's' : ''} not shown on map
    </div>
  {/if}
</div>

<style>
  .world-map {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .map-header {
    display: flex;
    justify-content: flex-end;
  }

  .map-stats {
    display: flex;
    gap: 1.5rem;
  }

  .stat {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 0.5rem 1rem;
    background: var(--neutral-50);
    border-radius: 0.375rem;
  }

  .stat-value {
    font-size: 1.25rem;
    font-weight: 700;
    color: var(--chilli-red);
  }

  .stat-label {
    font-size: 0.7rem;
    color: var(--neutral-500);
    text-transform: uppercase;
    letter-spacing: 0.025em;
  }

  .map-container {
    width: 100%;
    height: 400px;
    border-radius: 0.5rem;
    overflow: hidden;
    border: 1px solid var(--neutral-200);
    position: relative;
  }

  .map-loading {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background: rgba(255, 255, 255, 0.9);
    z-index: 1000;
    gap: 0.5rem;
    color: var(--neutral-600);
    font-size: 0.875rem;
  }

  .loading-spinner {
    width: 24px;
    height: 24px;
    border: 3px solid var(--neutral-200);
    border-top-color: var(--chilli-red);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .country-list {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.5rem;
    max-height: 200px;
    overflow-y: auto;
    padding-right: 0.5rem;
  }

  .country-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.375rem 0.5rem;
    background: var(--neutral-50);
    border-radius: 0.25rem;
  }

  .country-item.unmapped {
    opacity: 0.7;
  }

  .country-name {
    font-size: 0.75rem;
    color: var(--neutral-700);
    min-width: 100px;
    flex-shrink: 0;
  }

  .unmapped-indicator {
    color: var(--warning-orange);
    font-weight: bold;
  }

  .country-bar-container {
    flex: 1;
    height: 6px;
    background: var(--neutral-200);
    border-radius: 3px;
    overflow: hidden;
  }

  .country-bar {
    height: 100%;
    background: var(--chilli-red);
    border-radius: 3px;
    transition: width 0.3s ease;
  }

  .country-count {
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--neutral-600);
    min-width: 40px;
    text-align: right;
  }

  .unmapped-note {
    font-size: 0.7rem;
    color: var(--neutral-500);
    font-style: italic;
    text-align: center;
  }

  :global(.custom-marker) {
    background: transparent !important;
    border: none !important;
  }

  :global(.custom-marker .marker-container:hover) {
    transform: scale(1.1);
  }

  :global(.custom-popup .leaflet-popup-content-wrapper) {
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  }

  :global(.custom-popup .leaflet-popup-tip) {
    background: white;
  }

  :global(.leaflet-control-attribution) {
    font-size: 9px;
  }

  @media (max-width: 640px) {
    .country-list {
      grid-template-columns: 1fr;
    }

    .map-stats {
      gap: 1rem;
    }

    .map-container {
      height: 300px;
    }
  }

  @media print {
    .map-container {
      height: 300px;
    }
  }
</style>
